Repository eclipse-tractusx/tractusx-edc, pull requests merged in 2023-04, with the labels that each got.

#159 Remove lombok from edc tests
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/Connector.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/ConnectorFactory.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/Constants.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/ControlPlaneAdapterSteps.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/DataManagementAPI.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/Environment.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/HttpProxyTransferSteps.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/NegotiationSteps.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/PolicyStepDefs.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/S3FileTransferStepsDefs.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/Asset.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/BusinessPartnerNumberConstraint.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/ContractDefinition.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/ContractNegotiation.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/ContractOffer.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/HttpProxySourceDataAddress.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/Negotiation.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/OrConstraint.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/PayMeConstraint.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/Permission.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/Policy.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/S3DataAddress.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/Transfer.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/TransferProcess.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/util/DatabaseCleaner.java
  edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/util/S3Client.java
Labels: enhancement

#211 fix: Adapt Helm Chart for version 0.3.x
  .github/workflows/business-tests.yaml
  charts/tractusx-connector/templates/_helpers.tpl
  charts/tractusx-connector/templates/deployment-controlplane.yaml
  charts/tractusx-connector/templates/deployment-dataplane.yaml
  charts/tractusx-connector/templates/service-controlplane.yaml
  charts/tractusx-connector/templates/service-dataplane.yaml
  charts/tractusx-connector/values.yaml
  edc-dataplane/edc-dataplane-base/build.gradle.kts
Labels: bug

#252 chore: Add 0.3.3 to, and fix markdown in, CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#265 chore: Rename Veracode appname in CI job
  .github/workflows/veracode.yaml
Labels: gh-actions

#267 fix: Typo in veracode action
  .github/workflows/veracode.yaml
Labels: bug, gh-actions

#232 fix: Adapt Postman collection for 0.3.x
  docs/development/postman/collection.json
  docs/development/postman/images/screenshot.png
Labels: bug, enhancement

#138 feat: Add/update documentation for connector kit
  docs/development/Release.md
  docs/kit/adoption-view/images/domain-model.png
  docs/kit/adoption-view/images/edc_architecture.png
  docs/kit/adoption-view/images/edc_overview.png
  docs/kit/adoption-view/page_adoption-view.md
  docs/kit/adoption-view/page_domain_model.md
  docs/kit/development-view/page00_development_view.md
  docs/kit/development-view/page01_eclipse_foundation.md
  docs/kit/development-view/page02_repository_structure.md
  docs/kit/development-view/page03_project_structure.md
  docs/kit/operation-view/page00_operation_view.md
  docs/kit/operation-view/page02_technical_prerequisites.md
  docs/kit/operation-view/page03_local_setup_controlplane.md
  docs/kit/operation-view/page04_local_setup_dataplane.md
  docs/kit/operation-view/page06_kubernetes_setup.md
  docs/kit/operation-view/page08_api.md
  docs/kit/operation-view/page09_upgrading.md
  docs/kit/operation-view/page10_extensions.md
Labels: documentation

#273 build(deps): Move Gradle dependencies constrains into root build.gradle.kts
  build.gradle.kts
  edc-controlplane/edc-controlplane-postgresql/build.gradle.kts
  edc-dataplane/edc-dataplane-azure-vault/build.gradle.kts
  edc-extensions/control-plane-adapter/build.gradle.kts
Labels: dependencies

#276 feat: delete add-to-project workflow
  .github/workflows/add-to-project.yml
Labels: gh-actions

#282 chore: Update 3rd party DEPENDENCIES file
  DEPENDENCIES
Labels: dependencies

#285 chore: Add license and copyright header to the charts
  charts/tractusx-connector-memory/templates/configmap-runtime.yaml
  charts/tractusx-connector-memory/templates/deployment-runtime.yaml
  charts/tractusx-connector-memory/templates/hpa-runtime.yaml
  charts/tractusx-connector-memory/templates/ingress-runtime.yaml
  charts/tractusx-connector-memory/templates/service-runtime.yaml
  charts/tractusx-connector-memory/templates/serviceaccount.yaml
  charts/tractusx-connector-memory/templates/tests/test-readiness.yaml
  charts/tractusx-connector/templates/configmap-dataplane.yaml
  charts/tractusx-connector/templates/hpa-controlplane.yaml
  charts/tractusx-connector/templates/hpa-dataplane.yaml
  charts/tractusx-connector/templates/ingress-controlplane.yaml
  charts/tractusx-connector/templates/ingress-dataplane.yaml
  charts/tractusx-connector/templates/service-dataplane.yaml
  charts/tractusx-connector/templates/serviceaccount.yaml
  edc-tests/cucumber/src/main/resources/deployment/helm/supporting-infrastructure/values.yaml
Labels: documentation
