Repository eclipse-tractusx/tractusx-edc, pull requests merged in 2023-06, with the labels that each got.

#472 docs: add decision record about the use of iron-verifiable-credentials
  docs/development/decision-records/2023-06-13_use_of_iron_library/README.md
Labels: documentation

#475 feat(helm): use release.name inside daps dependency
  charts/tractusx-connector-azure-vault/subcharts/omejdn/templates/configmap.yaml
  charts/tractusx-connector-azure-vault/templates/deployment-controlplane.yaml
  charts/tractusx-connector-azure-vault/values.yaml
  charts/tractusx-connector-memory/example.yaml
  charts/tractusx-connector-memory/subcharts/omejdn/templates/configmap.yaml
  charts/tractusx-connector-memory/templates/deployment-runtime.yaml
  charts/tractusx-connector-memory/values.yaml
  charts/tractusx-connector/subcharts/omejdn/templates/configmap.yaml
  charts/tractusx-connector/templates/deployment-controlplane.yaml
  charts/tractusx-connector/values.yaml
  docs/samples/example-dataspace/daps/templates/configmap.yaml
  docs/samples/example-dataspace/plato-values.yaml
  docs/samples/example-dataspace/sokrates-values.yaml
  edc-tests/deployment/src/main/resources/helm/tractusx-connector-azure-vault-test.yaml
  edc-tests/deployment/src/main/resources/helm/tractusx-connector-test.yaml
Labels: helmcharts

#474 feat(helm): use release.name inside psql dependency
  charts/tractusx-connector-azure-vault/templates/deployment-controlplane.yaml
  charts/tractusx-connector-azure-vault/values.yaml
  charts/tractusx-connector/templates/deployment-controlplane.yaml
  charts/tractusx-connector/templates/deployment-dataplane.yaml
  charts/tractusx-connector/values.yaml
  edc-tests/deployment/src/main/resources/helm/tractusx-connector-test.yaml
Labels: helmcharts

#473 feat(helm): use release.name inside vault dependency
  charts/tractusx-connector/templates/deployment-controlplane.yaml
  charts/tractusx-connector/templates/deployment-dataplane.yaml
  charts/tractusx-connector/values.yaml
  edc-tests/deployment/src/main/resources/helm/tractusx-connector-test.yaml
Labels: helmcharts

#498 chore: remove in-mem vault
  edc-controlplane/edc-runtime-memory/build.gradle.kts
  edc-controlplane/edc-runtime-memory/src/main/java/org/eclipse/tractusx/edc/vault/memory/InMemoryVault.java
  edc-controlplane/edc-runtime-memory/src/main/java/org/eclipse/tractusx/edc/vault/memory/VaultSeedExtension.java
  edc-controlplane/edc-runtime-memory/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  edc-controlplane/edc-runtime-memory/src/test/java/org/eclipse/tractusx/edc/vault/memory/InMemoryVaultTest.java
  edc-controlplane/edc-runtime-memory/src/test/java/org/eclipse/tractusx/edc/vault/memory/VaultSeedExtensionTest.java
Labels: refactoring

#488 docs: Delete old "Local TXDC Setup.md"
  docs/samples/Local TXDC Setup.md
  docs/samples/README.md
Labels: documentation

#508 feat(build): only increase patch version on final releases
  .github/workflows/publish-new-release.yml
Labels: bug

#525 chore: upgrade to EDC 0.1.2
  edc-extensions/control-plane-adapter-api/src/test/java/org/eclipse/tractusx/edc/api/cp/adapter/transform/JsonObjectToNegotiateEdrRequestDtoTransformerTest.java
  edc-extensions/control-plane-adapter-callback/src/main/java/org/eclipse/tractusx/edc/cp/adapter/callback/InProcessCallbackMessageDispatcher.java
  gradle.properties
  gradle/libs.versions.toml
Labels: enhancement

#526 chore: prepare Changelog
  CHANGELOG.md
Labels: documentation

#530 refactor(build): restructure and serialize the build pipeline
  .github/workflows/deployment-test.yaml
  .github/workflows/publish-new-release.yml
  .github/workflows/publish.yaml
  .github/workflows/run-all-tests.yml
  .github/workflows/trivy.yml
  .github/workflows/verify.yaml
Labels: refactoring, gh-actions

#532 fix(build): use correct workflow name to trigger publish
  .github/workflows/publish.yaml
Labels: bug, gh-actions

#535 fix: Adapt Postman Collection for RC1/RC2
  docs/development/postman/collection.json
Labels: bug, documentation
