Repository eclipse-tractusx/tractusx-edc, pull requests merged in 2023-05, with the labels that each got.

#299 refactor(chart): move test infrastructure into the test chart
  .github/workflows/deployment-test.yaml
  charts/tractusx-connector-app/.helmignore
  charts/tractusx-connector-app/Chart.yaml
  charts/tractusx-connector-app/README.md
  charts/tractusx-connector-app/example.yaml
  charts/tractusx-connector-app/values.yaml
  edc-tests/deployment/src/main/resources/helm/test-infrastructure/Chart.yaml
  edc-tests/deployment/src/main/resources/helm/test-infrastructure/values.yaml
  edc-tests/deployment/src/main/resources/helm/tractusx-connector-test.yaml
Labels: bug

#317 docs: update code-of-conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#359 exclude charts/ from markdown lint, as the markdowns there are generated
  .github/workflows/verify.yaml
Labels: bug

#313 fix: add migration for transferprocess_properties default value
  edc-extensions/postgresql-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/transferprocess/V0_0_7__Default_Value_For_Properties.sql
Labels: bug

#358 fix: Rename ingress endpoint from ids to protocol
  charts/tractusx-connector-memory/templates/_helpers.tpl
  charts/tractusx-connector-memory/templates/deployment-runtime.yaml
  charts/tractusx-connector-memory/templates/service-runtime.yaml
  charts/tractusx-connector-memory/values.yaml
  charts/tractusx-connector/values.yaml
Labels: bug

#372 chore: remove duplicated helm-release workflow
  .github/workflows/helm-chart-release.yaml
  edc-tests/deployment/src/main/resources/helm/omejdn/templates/hpa.yaml
Labels: helmcharts, gh-actions

#383 fix(ci): store release version in env
  .github/actions/publish-docker-image/action.yml
  .github/workflows/build.yaml
  .github/workflows/publish-docker.yaml
  .github/workflows/publish-new-release.yml
Labels: bug

#404 feat: remove Lombok from HashiCorp Vault impl
  build.gradle.kts
  edc-controlplane/edc-controlplane-memory-hashicorp-vault/src/main/docker/Dockerfile
  edc-controlplane/edc-controlplane-postgresql-azure-vault/src/main/docker/Dockerfile
  edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/src/main/docker/Dockerfile
  edc-dataplane/edc-dataplane-azure-vault/src/main/docker/Dockerfile
  edc-dataplane/edc-dataplane-hashicorp-vault/src/main/docker/Dockerfile
  edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/AbstractHashicorpVaultExtension.java
  edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpCertificateResolver.java
  edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVault.java
  edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultClient.java
  edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultClientConfig.java
  edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultCreateEntryRequestPayload.java
  edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultCreateEntryResponsePayload.java
  edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultEntryMetadata.java
  edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultGetEntryResponsePayload.java
  edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultHealthCheck.java
  edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultHealthResponse.java
  edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultHealthResponsePayload.java
  edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultVaultExtension.java
  edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/PemUtil.java
  edc-extensions/hashicorp-vault/src/test/java/org/eclipse/tractusx/edc/hashicorpvault/AbstractHashicorpIt.java
  edc-extensions/hashicorp-vault/src/test/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpCertificateResolverIntegrationTest.java
  edc-extensions/hashicorp-vault/src/test/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpCertificateResolverTest.java
  edc-extensions/hashicorp-vault/src/test/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultClientTest.java
  edc-extensions/hashicorp-vault/src/test/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultHealthCheckTest.java
  edc-extensions/hashicorp-vault/src/test/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultTest.java
  edc-extensions/hashicorp-vault/src/test/java/org/eclipse/tractusx/edc/hashicorpvault/X509CertificateTestUtil.java
  lombok.config
Labels: refactoring

#424 chore: fix DAPS module dependency, update to java 17
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
Labels: bug, dependencies

#437 docs: add walkthrough for multi-connector setup
  docs/samples/example-dataspace/README.md
  docs/samples/example-dataspace/daps/.helmignore
  docs/samples/example-dataspace/daps/Chart.yaml
  docs/samples/example-dataspace/daps/README.md
  docs/samples/example-dataspace/daps/templates/_helpers.tpl
  docs/samples/example-dataspace/daps/templates/configmap.yaml
  docs/samples/example-dataspace/daps/templates/deployment.yaml
  docs/samples/example-dataspace/daps/templates/hpa.yaml
  docs/samples/example-dataspace/daps/templates/imagepullsecret.yaml
  docs/samples/example-dataspace/daps/templates/service.yaml
  docs/samples/example-dataspace/daps/templates/serviceaccount.yaml
  docs/samples/example-dataspace/daps/values.yaml
  docs/samples/example-dataspace/plato-values.yaml
  docs/samples/example-dataspace/sokrates-values.yaml
Labels: documentation, helmcharts

#438 chore: update changelog
  CHANGELOG.md
Labels: documentation

#440 fix: limit search for Chart.yaml to avoid subchart updates
  .github/workflows/draft-new-release.yaml
  CHANGELOG.md
  charts/tractusx-connector-azure-vault/subcharts/omejdn/Chart.yaml
  charts/tractusx-connector/subcharts/omejdn/Chart.yaml
Labels: bug
