Repository eclipse-tractusx/tractusx-edc, pull requests merged in 2023-12, with the labels that each got.

#906 chore: deactivate azure tests temporarily
  .github/workflows/deployment-test.yaml
Labels: bug, gh-actions

#910 chore: add legal info to Docker images
  NOTICE.md
  build.gradle.kts
  edc-controlplane/edc-controlplane-postgresql-azure-vault/notice.md
  edc-controlplane/edc-controlplane-postgresql-azure-vault/src/main/docker/Dockerfile
  edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/notice.md
  edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/src/main/docker/Dockerfile
  edc-controlplane/edc-runtime-memory/src/main/docker/Dockerfile
  edc-dataplane/edc-dataplane-azure-vault/notice.md
  edc-dataplane/edc-dataplane-azure-vault/src/main/docker/Dockerfile
  edc-dataplane/edc-dataplane-hashicorp-vault/notice.md
  edc-dataplane/edc-dataplane-hashicorp-vault/src/main/docker/Dockerfile
Labels: documentation, enhancement

#911 chore: add notice section to markdown files
  docs/README.md
  docs/development/Release.md
  docs/development/coding-principles.md
  docs/development/decision-records/2023-02-09-release-process/README.md
  docs/development/decision-records/2023-02-27_testing/README.md
  docs/development/decision-records/2023-03-02_gradle_build/README.md
  docs/development/decision-records/2023-03-23_remove_lombok/README.md
  docs/development/decision-records/2023-04-03_renaming_branches/README.md
  docs/development/decision-records/2023-04-11_refactor_helmcharts/README.md
  docs/development/decision-records/2023-04-20_conventional_commits/README.md
  docs/development/decision-records/2023-05-23_activate_checkstyle/README.md
  docs/development/decision-records/2023-05-23_java_17_baseline/README.md
  docs/development/decision-records/2023-06-13_use_of_iron_library/README.md
  docs/development/decision-records/2023-07-06_removing_manual_changelog/README.md
  docs/development/decision-records/2023-08-03_improve_bpn_validation/README.md
  docs/development/decision-records/2023-08-24-proprietrary-extensions/README.md
  docs/development/decision-records/2023-09-08_issue_quality_stalebot/README.md
  docs/development/postman/README.md
  docs/development/scripts/daps_token/README.md
  docs/development/scripts/daps_token/daps_auth.sh
  docs/development/scripts/daps_token/key.pem
  docs/kit/Adoption View/00_adoption-view.md
  docs/kit/Development View/01_domain_model.md
  docs/kit/Development View/02_OpenAPI/00_open_api.md
  docs/kit/Development View/05_EDC Extensions/00_extensions.md
  docs/kit/Documentation/00_repository_structure.md
  docs/kit/Documentation/01_project_structure.md
  docs/kit/Operation View/00_operation_view.md
  docs/kit/Operation View/01_technical_prerequisites.md
  docs/kit/Operation View/02_Local Setup/00_local_setup_controlplane.md
  docs/kit/Operation View/02_Local Setup/01_local_setup_dataplane.md
  docs/kit/Operation View/04_Test Your Setup/01_api.md
  docs/kit/Operation View/05_Migration/00_upgrading.md
  docs/migration/Version_0.0.x_0.1.x.md
  docs/migration/Version_0.1.0_0.1.1.md
  docs/migration/Version_0.1.2_0.1.3.md
  docs/migration/Version_0.1.x_0.3.x.md
  docs/migration/Version_0.3.0_0.3.1.md
  docs/migration/Version_0.3.1_0.3.2.md
  docs/migration/Version_0.3.3_0.3.4.md
  docs/migration/Version_0.3.4_0.4.0.md
  docs/migration/Version_0.4.x_0.5.x.md
  docs/release-notes/Version 0.1.0.md
  docs/release-notes/Version 0.1.1.md
  docs/release-notes/Version 0.1.2.md
  docs/release-notes/Version 0.1.3.md
  docs/release-notes/Version 0.1.5.md
  docs/samples/README.md
  docs/samples/Transfer Data.md
  docs/samples/example-dataspace/README.md
Labels: documentation

#912 feat(test): add upgradeability test for Helm charts
  .github/workflows/run-all-tests.yml
  .github/workflows/upgradeability-test.yaml
Labels: helmcharts, gh-actions

#905 chore: remove markdown linter
  .github/workflows/verify.yaml
  .markdownlint.yaml
Labels: gh-actions

#932 refactor: cleanup DAPS references
  DEPENDENCIES
  docs/README.md
  docs/development/README.md
  docs/development/data-plane-http-oauth2.md
  docs/development/edr-api-overview.md
  docs/development/run-config.png
  docs/kit/Adoption View/00_adoption-view.md
  docs/kit/Operation View/02_Local Setup/00_local_setup_controlplane.md
  docs/samples/README.md
  docs/samples/Transfer Data.md
  docs/samples/diagrams/transfer_sequence_1.png
  docs/samples/diagrams/transfer_sequence_1.puml
  docs/samples/diagrams/transfer_sequence_2.png
  docs/samples/diagrams/transfer_sequence_2.puml
  docs/samples/diagrams/transfer_sequence_3.png
  docs/samples/diagrams/transfer_sequence_3.puml
  docs/samples/diagrams/transfer_sequence_4.png
  docs/samples/diagrams/transfer_sequence_4.puml
  docs/samples/diagrams/transfer_sequence_5.png
  docs/samples/diagrams/transfer_sequence_5.puml
  docs/samples/example-dataspace/README.md
  docs/samples/example-dataspace/plato-values.yaml
  docs/samples/example-dataspace/sokrates-values.yaml
  edc-controlplane/edc-controlplane-postgresql-azure-vault/README.md
  edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/README.md
  edc-controlplane/edc-runtime-memory/README.md
  edc-dataplane/edc-dataplane-azure-vault/README.md
  edc-dataplane/edc-dataplane-hashicorp-vault/README.md
  edc-extensions/build.gradle.kts
  edc-extensions/cx-oauth2/README.md
  edc-extensions/cx-oauth2/build.gradle.kts
  edc-extensions/cx-oauth2/diagrams/sequence.png
  edc-extensions/cx-oauth2/diagrams/sequence.puml
  edc-extensions/cx-oauth2/src/main/java/org/eclipse/tractusx/edc/oauth2/CxOauth2Extension.java
  edc-extensions/cx-oauth2/src/main/java/org/eclipse/tractusx/edc/oauth2/CxParticipantExtension.java
  edc-extensions/cx-oauth2/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  edc-extensions/cx-oauth2/src/test/java/org/eclipse/tractusx/edc/oauth2/CxParticipantExtensionTest.java
  edc-tests/deployment/src/main/resources/helm/tractusx-connector-azure-vault-test.yaml
  edc-tests/deployment/src/main/resources/helm/tractusx-connector-memory-test.yaml
  edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/lifecycle/ParticipantRuntime.java
  edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/lifecycle/PgParticipantRuntime.java
  edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/token/MockBpnIdentityService.java
  edc-tests/runtime/runtime-memory-ssi/build.gradle.kts
  edc-tests/runtime/runtime-memory/build.gradle.kts
  edc-tests/runtime/runtime-postgresql-hashicorp/build.gradle.kts
  edc-tests/runtime/runtime-postgresql/build.gradle.kts
  gradle/libs.versions.toml
  samples/multi-tenancy/build.gradle.kts
  settings.gradle.kts
Labels: documentation, refactoring

#949 feat: switch assets_selector type from text to json
  edc-extensions/postgresql-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/contractdefinition/V0_0_8__Alter_ContractDefinition_Switch_Assets_Selector_Json.sql
Labels: enhancement
