Repository eclipse-tractusx/tractusx-edc, pull requests merged in 2023-08, with the labels that each got.

#716 chore: update to EDC 0.2.1
  .github/workflows/verify.yaml
  DEPENDENCIES
  core/edr-cache-core/src/main/java/org/eclipse/tractusx/edc/edr/core/defaults/EdrCacheEntryPredicateConverter.java
  edc-extensions/dataplane-proxy/edc-dataplane-proxy-consumer-api/src/test/java/org/eclipse/tractusx/edc/dataplane/proxy/consumer/api/asset/model/ConsumerAssetRequestControllerTest.java
  edc-extensions/edr/edr-api/src/test/java/org/eclipse/tractusx/edc/api/edr/transform/EndpointDataReferenceToDataAddressTransformerTest.java
  edc-extensions/edr/edr-callback/src/test/java/org/eclipse/tractusx/edc/callback/ContractNegotiationCallbackTest.java
  edc-extensions/postgresql-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/contractnegotiation/V0_0_7__Alter_ContractNegotiation_AddPendingField.sql
  edc-extensions/transferprocess-sftp-client/src/main/java/org/eclipse/tractusx/edc/transferprocess/sftp/client/SftpDataSinkFactory.java
  edc-extensions/transferprocess-sftp-client/src/main/java/org/eclipse/tractusx/edc/transferprocess/sftp/client/SftpDataSourceFactory.java
  edc-extensions/transferprocess-sftp-client/src/test/java/org/eclipse/tractusx/edc/transferprocess/sftp/client/SftpDataSinkFactoryTest.java
  edc-extensions/transferprocess-sftp-client/src/test/java/org/eclipse/tractusx/edc/transferprocess/sftp/client/SftpDataSourceFactoryTest.java
  edc-extensions/transferprocess-sftp-common/src/main/java/org/eclipse/tractusx/edc/transferprocess/sftp/common/SftpDataAddress.java
  edc-extensions/transferprocess-sftp-common/src/test/java/org/eclipse/tractusx/edc/transferprocess/sftp/common/SftpDataAddressTest.java
  gradle.properties
  gradle/libs.versions.toml
Labels: enhancement, edc, critical

#722 chore: add LICENSE file to all charts
  charts/tractusx-connector-azure-vault/LICENSE
  charts/tractusx-connector-memory/LICENSE
  charts/tractusx-connector/LICENSE
Labels: helmcharts, critical

#727 fix(build): fix docker image inspect command
  .github/workflows/trivy.yml
  DEPENDENCIES
Labels: bug

#733 chore(changelog): updated CHANGELOG.md with 0.5.0 and 0.5.1
  CHANGELOG.md
Labels: documentation
