Repository eclipse-tractusx/tractusx-edc, pull requests merged in 2023-10, with the labels that each got.

#806 chore: updates to EDC 0.3.1
  DEPENDENCIES
  edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/edr/AbstractNegotiateEdrTest.java
  edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/edr/AbstractRenewalEdrTest.java
  edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/proxy/AbstractDataPlaneProxyTest.java
  edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/AbstractHttpConsumerPullWithProxyTest.java
  edc-tests/runtime/extensions/src/main/java/org/eclipse/tractusx/edc/lifecycle/TestServiceExtension.java
  edc-tests/runtime/extensions/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  gradle/libs.versions.toml
Labels: dependencies

#801 feat(SqlEdrStore): add configurable vault path
  DEPENDENCIES
  edc-extensions/edr/edr-cache-sql/README.md
  edc-extensions/edr/edr-cache-sql/src/main/java/org/eclipse/tractusx/edc/edr/store/sql/SqlEndpointDataReferenceCache.java
  edc-extensions/edr/edr-cache-sql/src/main/java/org/eclipse/tractusx/edc/edr/store/sql/SqlEndpointDataReferenceCacheExtension.java
  edc-extensions/edr/edr-cache-sql/src/test/java/org/eclipse/tractusx/edc/edr/store/sql/SqlEndpointDataReferenceCacheTest.java
  edc-extensions/edr/edr-cache-sql/src/test/java/org/eclipse/tractusx/edc/edr/store/sql/SqlEndpointDataReferenceCacheTransactionalTest.java
  edc-tests/e2e-tests/build.gradle.kts
  edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/lifecycle/PgHashicorpParticipantRuntime.java
  edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/lifecycle/PgParticipantRuntime.java
  edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/edr/NegotiateEdrPostgresqlHashicorpVaultTest.java
  edc-tests/runtime/runtime-postgresql-hashicorp/README.md
  edc-tests/runtime/runtime-postgresql-hashicorp/build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: enhancement

#820 docs: set openapi default version on swaggerhub
  .github/workflows/publish-swaggerhub.yaml
Labels: documentation

#822 fix: add removed setting from publish workflow
  .github/workflows/publish.yaml
Labels: bug
