Repository eclipse-tractusx/tractusx-edc, pull requests merged in 2023-07, with the labels that each got.

#553 refactor: Remove observability-api-customization and use upstream extension
  CHANGELOG.md
  charts/tractusx-connector-azure-vault/README.md
  charts/tractusx-connector-azure-vault/templates/deployment-controlplane.yaml
  charts/tractusx-connector-azure-vault/templates/deployment-dataplane.yaml
  charts/tractusx-connector-azure-vault/templates/service-controlplane.yaml
  charts/tractusx-connector-azure-vault/templates/service-dataplane.yaml
  charts/tractusx-connector-azure-vault/templates/tests/test-controlplane-readiness.yaml
  charts/tractusx-connector-azure-vault/templates/tests/test-dataplane-readiness.yaml
  charts/tractusx-connector-azure-vault/values.yaml
  charts/tractusx-connector-legacy/README.md
  charts/tractusx-connector-legacy/templates/deployment-controlplane.yaml
  charts/tractusx-connector-legacy/templates/deployment-dataplane.yaml
  charts/tractusx-connector-legacy/templates/service-controlplane.yaml
  charts/tractusx-connector-legacy/templates/service-dataplane.yaml
  charts/tractusx-connector-legacy/templates/tests/test-controlplane-readiness.yaml
  charts/tractusx-connector-legacy/templates/tests/test-dataplane-readiness.yaml
  charts/tractusx-connector-legacy/values.yaml
  charts/tractusx-connector-memory/README.md
  charts/tractusx-connector-memory/templates/deployment-runtime.yaml
  charts/tractusx-connector-memory/templates/service-runtime.yaml
  charts/tractusx-connector-memory/templates/tests/test-readiness.yaml
  charts/tractusx-connector-memory/values.yaml
  charts/tractusx-connector/README.md
  charts/tractusx-connector/templates/deployment-controlplane.yaml
  charts/tractusx-connector/templates/deployment-dataplane.yaml
  charts/tractusx-connector/templates/service-controlplane.yaml
  charts/tractusx-connector/templates/service-dataplane.yaml
  charts/tractusx-connector/templates/tests/test-controlplane-readiness.yaml
  charts/tractusx-connector/templates/tests/test-dataplane-readiness.yaml
  charts/tractusx-connector/values.yaml
  docs/migration/Version_0.4.x_0.5.x.md
  edc-controlplane/edc-controlplane-base/build.gradle.kts
  edc-controlplane/edc-controlplane-postgresql-hashicorp-vault-legacy/build.gradle.kts
  edc-dataplane/edc-dataplane-base/build.gradle.kts
  edc-extensions/observability-api-customization/README.md
  edc-extensions/observability-api-customization/build.gradle.kts
  edc-extensions/observability-api-customization/src/main/java/org/eclipse/tractusx/edc/api/observability/TxObservabilityApi.java
  edc-extensions/observability-api-customization/src/main/java/org/eclipse/tractusx/edc/api/observability/TxObservabilityApiController.java
  edc-extensions/observability-api-customization/src/main/java/org/eclipse/tractusx/edc/api/observability/TxObservabilityApiExtension.java
  edc-extensions/observability-api-customization/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  edc-extensions/observability-api-customization/src/test/java/org/eclipse/tractusx/edc/api/observability/TxObservabilityApiControllerTest.java
  edc-extensions/observability-api-customization/src/test/java/org/eclipse/tractusx/edc/api/observability/TxObservabilityApiExtensionTest.java
  settings.gradle.kts
Labels: refactoring

#519 docs: adds EDR API overview documentation
  docs/samples/edr-api-overview/edr-api-overview.md
Labels: documentation

#566 feat: update DEPENDENCIES, add check to CI
  .github/workflows/verify.yaml
  DEPENDENCIES
Labels: bug, documentation, gh-actions

#576 feat(docs): adds more information on MIW credential module
  edc-extensions/ssi/ssi-miw-credential-client/README.md
Labels: documentation

#583 feat: remove `CHANGELOG.md`, generate automatically
  .github/workflows/draft-new-release.yaml
  .github/workflows/publish-new-release.yml
  CHANGELOG.md
Labels: enhancement, gh-actions

#607 chore: Improve Helm Chart documentation
  charts/tractusx-connector-azure-vault/README.md
  charts/tractusx-connector-azure-vault/values.yaml
  charts/tractusx-connector-legacy/README.md
  charts/tractusx-connector-legacy/values.yaml
  charts/tractusx-connector-memory/README.md
  charts/tractusx-connector-memory/values.yaml
  charts/tractusx-connector/README.md
  charts/tractusx-connector/values.yaml
Labels: documentation, helmcharts

#633 chore: update curl version to 8.2.0-r0
  DEPENDENCIES
  edc-controlplane/edc-controlplane-memory-hashicorp-vault/src/main/docker/Dockerfile
  edc-controlplane/edc-controlplane-postgresql-azure-vault/src/main/docker/Dockerfile
  edc-controlplane/edc-controlplane-postgresql-hashicorp-vault-legacy/src/main/docker/Dockerfile
  edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/src/main/docker/Dockerfile
  edc-dataplane/edc-dataplane-azure-vault/src/main/docker/Dockerfile
  edc-dataplane/edc-dataplane-hashicorp-vault/src/main/docker/Dockerfile
Labels: enhancement

#678 feat: simplify data encryptor
  .github/workflows/verify.yaml
  edc-extensions/data-encryption/README.md
  edc-extensions/data-encryption/build.gradle.kts
  edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/ArrayUtil.java
  edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/DataEncryptionExtension.java
  edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/TxEncryptorExtension.java
  edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/aes/AesEncryptor.java
  edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/algorithms/CryptoAlgorithm.java
  edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/algorithms/aes/AesAlgorithm.java
  edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/algorithms/aes/AesInitializationVectorIterator.java
  edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/algorithms/aes/ByteCounter.java
  edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/data/CryptoData.java
  edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/data/CryptoDataFactoryImpl.java
  edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/data/DecryptedData.java
  edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/data/EncryptedData.java
  edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/encrypter/AesDataEncrypterConfiguration.java
  edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/encrypter/AesDataEncrypterImpl.java
  edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/encrypter/DataEncrypterFactory.java
  edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/key/AesKey.java
  edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/key/CryptoKey.java
  edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/key/CryptoKeyFactory.java
  edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/key/CryptoKeyFactoryImpl.java
  edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/provider/AesKeyProvider.java
  edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/provider/CachingKeyProvider.java
  edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/provider/KeyProvider.java
  edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/util/ArrayUtil.java
  edc-extensions/data-encryption/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  edc-extensions/data-encryption/src/test/java/org/eclipse/tractusx/edc/data/encryption/DataEncryptionExtensionTest.java
  edc-extensions/data-encryption/src/test/java/org/eclipse/tractusx/edc/data/encryption/TxEncryptorExtensionTest.java
  edc-extensions/data-encryption/src/test/java/org/eclipse/tractusx/edc/data/encryption/aes/AesEncryptorTest.java
  edc-extensions/data-encryption/src/test/java/org/eclipse/tractusx/edc/data/encryption/algorithms/aes/AesAlgorithmTest.java
  edc-extensions/data-encryption/src/test/java/org/eclipse/tractusx/edc/data/encryption/algorithms/aes/AesInitializationVectorIteratorTest.java
  edc-extensions/data-encryption/src/test/java/org/eclipse/tractusx/edc/data/encryption/algorithms/aes/ByteCounterTest.java
  edc-extensions/data-encryption/src/test/java/org/eclipse/tractusx/edc/data/encryption/encrypter/DataEncrypterAesComponentTest.java
  edc-extensions/data-encryption/src/test/java/org/eclipse/tractusx/edc/data/encryption/encrypter/DataEncrypterFactoryTest.java
  edc-extensions/data-encryption/src/test/java/org/eclipse/tractusx/edc/data/encryption/key/CryptoKeyFactoryImplTest.java
  edc-extensions/data-encryption/src/test/java/org/eclipse/tractusx/edc/data/encryption/provider/AesKeyProviderTest.java
  edc-extensions/data-encryption/src/test/java/org/eclipse/tractusx/edc/data/encryption/provider/CachingKeyProviderTest.java
  edc-extensions/data-encryption/src/test/java/org/eclipse/tractusx/edc/data/encryption/util/ArrayUtilTest.java
  edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/lifecycle/PgParticipantRuntime.java
  edc-tests/runtime/extensions/src/main/java/org/eclipse/tractusx/edc/lifecycle/TestServiceExtension.java
Labels: enhancement
