Repository eclipse-tractusx/tractusx-edc, pull requests merged in 2024-03, with the labels that each got.

#1104 docs: add support documentation for DataPlane Signaling
  docs/development/dataplane-signaling/AutomaticRefresh.drawio
  docs/development/dataplane-signaling/AutomaticRefresh.drawio.png
  docs/development/dataplane-signaling/ManualRefresh.drawio
  docs/development/dataplane-signaling/ManualRefresh.drawio.png
  docs/development/dataplane-signaling/TxSignaling.drawio
  docs/development/dataplane-signaling/TxSignaling.drawio.png
  docs/development/dataplane-signaling/tx-signaling.extensions.md
Labels: documentation

#1118 chore: fix compile error after upstream transformers refactor
  DEPENDENCIES
  edc-extensions/edr/edr-api/src/test/java/org/eclipse/tractusx/edc/api/edr/EdrApiTest.java
Labels: bug

#1123 docs: improve token refresh docu
  docs/development/dataplane-signaling/AutomaticRefreshEdrApi.drawio
  docs/development/dataplane-signaling/AutomaticRefreshEdrApi.drawio.png
  docs/development/dataplane-signaling/ManualRefresh.drawio
  docs/development/dataplane-signaling/ManualRefresh.drawio.png
  docs/development/dataplane-signaling/tx-signaling.extensions.md
Labels: documentation, enhancement

#1124 fix: add expiry check to DataPlaneTokenRefreshServiceImpl
  edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/main/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceExtension.java
  edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/main/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceImpl.java
  edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/test/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceImplComponentTest.java
  edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/test/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceImplTest.java
Labels: bug

#1126 feat: add TokenRefreshHandler
  DEPENDENCIES
  edc-extensions/README.md
  edc-extensions/dataplane/dataplane-token-refresh/token-refresh-api/src/main/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/api/TokenRefreshApiExtension.java
  edc-extensions/dataplane/dataplane-token-refresh/token-refresh-api/src/main/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/api/v1/TokenRefreshApi.java
  edc-extensions/dataplane/dataplane-token-refresh/token-refresh-api/src/main/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/api/v1/TokenRefreshApiController.java
  edc-extensions/dataplane/dataplane-token-refresh/token-refresh-api/src/test/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/api/v1/TokenRefreshApiControllerTest.java
  edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/main/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceExtension.java
  edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/main/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceImpl.java
  edc-extensions/tokenrefresh-handler/build.gradle.kts
  edc-extensions/tokenrefresh-handler/src/main/java/org/eclipse/tractusx/edc/common/tokenrefresh/TokenRefreshHandlerExtension.java
  edc-extensions/tokenrefresh-handler/src/main/java/org/eclipse/tractusx/edc/common/tokenrefresh/TokenRefreshHandlerImpl.java
  edc-extensions/tokenrefresh-handler/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  edc-extensions/tokenrefresh-handler/src/test/java/org/eclipse/tractusx/edc/common/tokenrefresh/TokenRefreshHandlerImplTest.java
  edc-tests/edc-dataplane/edc-dataplane-tokenrefresh-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/e2e/DataPlaneTokenRefreshEndToEndTest.java
  gradle/libs.versions.toml
  settings.gradle.kts
  spi/tokenrefresh-spi/src/main/java/org/eclipse/tractusx/edc/spi/tokenrefresh/common/TokenRefreshHandler.java
  spi/tokenrefresh-spi/src/main/java/org/eclipse/tractusx/edc/spi/tokenrefresh/dataplane/DataPlaneTokenRefreshService.java
  spi/tokenrefresh-spi/src/main/java/org/eclipse/tractusx/edc/spi/tokenrefresh/dataplane/model/TokenResponse.java
Labels: Feature, critical

#856 doc(policies): add policy description in tractusx-edc
  docs/usage/management-api-walkthrough/02_policies.md
Labels: documentation

#1135 feature(api): Update NegotiateEdrRequestDto
  edc-extensions/edr/edr-api/src/main/java/org/eclipse/tractusx/edc/api/edr/EdrApiExtension.java
  edc-extensions/edr/edr-api/src/main/java/org/eclipse/tractusx/edc/api/edr/dto/NegotiateEdrRequestDto.java
  edc-extensions/edr/edr-api/src/main/java/org/eclipse/tractusx/edc/api/edr/schema/EdrSchema.java
  edc-extensions/edr/edr-api/src/main/java/org/eclipse/tractusx/edc/api/edr/transform/JsonObjectToNegotiateEdrRequestDtoTransformer.java
  edc-extensions/edr/edr-api/src/main/java/org/eclipse/tractusx/edc/api/edr/transform/NegotiateEdrRequestDtoToNegotiatedEdrRequestTransformer.java
  edc-extensions/edr/edr-api/src/main/java/org/eclipse/tractusx/edc/api/edr/validation/NegotiateEdrRequestDtoValidator.java
  edc-extensions/edr/edr-api/src/test/java/org/eclipse/tractusx/edc/api/edr/EdrApiTest.java
  edc-extensions/edr/edr-api/src/test/java/org/eclipse/tractusx/edc/api/edr/TestFunctions.java
  edc-extensions/edr/edr-api/src/test/java/org/eclipse/tractusx/edc/api/edr/transform/JsonObjectToNegotiateEdrRequestDtoTransformerTest.java
  edc-extensions/edr/edr-api/src/test/java/org/eclipse/tractusx/edc/api/edr/transform/NegotiateEdrRequestDtoToNegotiateEdrRequestTransformerTest.java
  edc-extensions/edr/edr-api/src/test/java/org/eclipse/tractusx/edc/api/edr/validation/NegotiateEdrRequestDtoValidatorTest.java
Labels: enhancement, refactoring

#1143 chore: add CodeQL workflow
  .github/workflows/codeql.yaml
  .github/workflows/veracode.yaml
Labels: gh-actions, github-actions

#1166 fix: compile errors after upstream refactor
  DEPENDENCIES
  build.gradle.kts
  charts/tractusx-connector-azure-vault/templates/deployment-controlplane.yaml
  charts/tractusx-connector-memory/templates/deployment-runtime.yaml
  charts/tractusx-connector/templates/deployment-controlplane.yaml
  core/edr-cache-core/build.gradle.kts
  core/edr-cache-core/src/test/java/org/eclipse/tractusx/edc/edr/core/defaults/InMemoryEndpointDataReferenceCacheTest.java
  edc-controlplane/edc-controlplane-base/build.gradle.kts
  edc-controlplane/edc-runtime-memory/build.gradle.kts
  edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/build.gradle.kts
  edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/test/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceImplComponentTest.java
  edc-tests/miw-tests/build.gradle.kts
  edc-tests/runtime/iatp/runtime-memory-iatp-dim-ih/build.gradle.kts
  edc-tests/runtime/iatp/runtime-memory-iatp-dim/build.gradle.kts
  edc-tests/runtime/iatp/runtime-memory-iatp-ih/build.gradle.kts
  edc-tests/runtime/iatp/runtime-memory-sts/build.gradle.kts
  edc-tests/runtime/runtime-memory-ssi/build.gradle.kts
  edc-tests/runtime/runtime-postgresql/build.gradle.kts
  gradle/libs.versions.toml
  samples/multi-tenancy/build.gradle.kts
  samples/multi-tenancy/src/main/java/org/eclipse/tractusx/edc/samples/multitenancy/MultiTenantRuntime.java
  spi/ssi-spi/build.gradle.kts
Labels: bug

#1165 feat: add BDRS client w/ expiring cache
  DEPENDENCIES
  build.gradle.kts
  edc-extensions/bdrs-client/build.gradle.kts
  edc-extensions/bdrs-client/src/main/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClient.java
  edc-extensions/bdrs-client/src/main/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientExtension.java
  edc-extensions/bdrs-client/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  edc-extensions/bdrs-client/src/test/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientExtensionTest.java
  edc-extensions/bdrs-client/src/test/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientTest.java
  settings.gradle.kts
Labels: enhancement, critical

#1168 chore(build): updates to EDC 0.6.0
  DEPENDENCIES
  core/edr-core/build.gradle.kts
  edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/build.gradle.kts
  edc-extensions/edr/edr-api-v2/build.gradle.kts
  edc-extensions/edr/edr-api/build.gradle.kts
  edc-extensions/transferprocess-sftp-client/build.gradle.kts
  edc-extensions/transferprocess-sftp-provisioner/build.gradle.kts
  edc-tests/edc-controlplane/fixtures/build.gradle.kts
  gradle/libs.versions.toml
Labels: dependencies
