Repository eclipse-tractusx/tractusx-edc, pull requests merged in 2024-07, with the labels that each got.

#1399 docs(api): fix published api specs
  .github/workflows/publish-swaggerhub.yaml
Labels: bug, dependencies

#1402 docs(api): get openapi files from dependencies repository
  .github/workflows/publish-swaggerhub.yaml
  DEPENDENCIES
  build.gradle.kts
  edc-extensions/migrations/postgresql-migration-lib/build.gradle.kts
  edc-tests/edc-controlplane/catalog-tests/build.gradle.kts
  edc-tests/edc-controlplane/fixtures/build.gradle.kts
  edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/runtimes/ParticipantRuntimeExtension.java
  edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/runtimes/PgRuntimeExtension.java
  edc-tests/runtime/runtime-postgresql/build.gradle.kts
  gradle/libs.versions.toml
Labels: documentation

#1398 doc: Add concept document for Bidirectional Data Transfer
  docs/development/bidirectional-transfer/BidirectionalDataTransfer.md
Labels: documentation

#1425 docs: publish openapi-ui to github pages
  .github/workflows/publish-openapi-ui.yml
Labels: documentation

#1431 docs: decisio-record abour versioning scheme
  docs/development/decision-records/2024-07-18-Improvements-versioning-scheme/README.md
Labels: documentation

#1428 docs: split openapi spec by plane
  .github/workflows/publish-openapi-ui.yml
  .github/workflows/publish-swaggerhub.yaml
  edc-extensions/bpn-validation/bpn-validation-api/build.gradle.kts
  edc-extensions/dataplane/dataplane-proxy/edc-dataplane-proxy-consumer-api/build.gradle.kts
  edc-extensions/dataplane/dataplane-token-refresh/token-refresh-api/build.gradle.kts
  edc-extensions/edr/edr-api-v2/build.gradle.kts
  edc-tests/runtime/mock-connector/build.gradle.kts
  gradle/libs.versions.toml
Labels: documentation

#1434 docs: fix publish-ui
  .github/workflows/publish-openapi-ui.yml
Labels: documentation

#1435 docs: fix publish openapi-ui folder
  .github/workflows/publish-openapi-ui.yml
Labels: documentation

#1442 chore(ci): update Kubernetes versions
  .github/workflows/deployment-test.yaml
  DEPENDENCIES
Labels: enhancement, gh-actions

#1430 refactor: avoid Dockerfile duplication
  .github/actions/publish-docker-image/action.yml
  .github/actions/run-deployment-test/action.yml
  .github/dependabot.yml
  .github/workflows/deployment-test.yaml
  DEPENDENCIES
  build.gradle.kts
  edc-controlplane/edc-controlplane-postgresql-azure-vault/notice.md
  edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/notice.md
  edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/src/main/docker/Dockerfile
  edc-controlplane/edc-runtime-memory/notice.md
  edc-controlplane/edc-runtime-memory/src/main/docker/Dockerfile
  edc-dataplane/edc-dataplane-azure-vault/notice.md
  edc-dataplane/edc-dataplane-azure-vault/src/main/docker/Dockerfile
  edc-dataplane/edc-dataplane-hashicorp-vault/notice.md
  edc-dataplane/edc-dataplane-hashicorp-vault/src/main/docker/Dockerfile
  edc-tests/runtime/mock-connector/notice.md
  edc-tests/runtime/mock-connector/src/main/docker/Dockerfile
  resources/Dockerfile
  samples/edc-dast/edc-dast-runtime/src/main/docker/Dockerfile
Labels: refactoring

#1451 build(dependencies): Fix dependabot docker directory
  .github/dependabot.yml
Labels: dependencies

#1455 feat(ci): publish workflows call reusable trigger workflows
  .github/workflows/publish-new-release.yml
  .github/workflows/publish-new-snapshot.yaml
  .github/workflows/trigger-maven-publish.yaml
Labels: enhancement, gh-actions

#1458 build: change copyDockerfile output path
  .github/actions/publish-docker-image/action.yml
  build.gradle.kts
Labels: enhancement, docker

#1459 feat(ci): add periodic build trigger
  .github/workflows/publish-new-release.yml
  .github/workflows/publish-new-snapshot.yaml
  .github/workflows/publish-openapi-ui.yml
  .github/workflows/run-all-tests.yml
  .github/workflows/trigger-docker-publish.yaml
  .github/workflows/trigger-maven-publish.yaml
Labels: enhancement, gh-actions

#1460 feat: remove project root from the docker image
  .github/actions/publish-docker-image/action.yml
  DEPENDENCIES
  build.gradle.kts
  edc-controlplane/edc-controlplane-postgresql-azure-vault/build.gradle.kts
  edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/build.gradle.kts
  edc-controlplane/edc-runtime-memory/build.gradle.kts
  edc-dataplane/edc-dataplane-azure-vault/build.gradle.kts
  edc-dataplane/edc-dataplane-hashicorp-vault/build.gradle.kts
  edc-tests/runtime/mock-connector/build.gradle.kts
  gradle/libs.versions.toml
  samples/edc-dast/edc-dast-runtime/build.gradle.kts
Labels: enhancement

#1461 build: add write contents permission to deploy-swagger-ui
  .github/workflows/publish-openapi-ui.yml
Labels: gh-actions

#1463 build: fix dependency scope for libs.edc.junit
  DEPENDENCIES
  edc-extensions/dataplane/dataplane-selector-configuration/build.gradle.kts
  edc-extensions/migrations/control-plane-migration/build.gradle.kts
  edc-extensions/migrations/data-plane-migration/build.gradle.kts
  edc-extensions/migrations/postgresql-migration-lib/build.gradle.kts
Labels: enhancement

#1468 fix(ci): remove obsolete workflow parameter `do_push`
  .github/workflows/trigger-docker-publish.yaml
Labels: bug

#1469 Bump EDC to 0.8.1
  DEPENDENCIES
  edc-controlplane/edc-controlplane-base/build.gradle.kts
  edc-extensions/migrations/control-plane-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/policy/V0_0_5__Add_Profiles.sql
  edc-tests/edc-controlplane/catalog-tests/src/test/java/org/eclipse/tractusx/edc/tests/catalog/FederatedCatalogTest.java
  edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/runtimes/PgRuntimeExtension.java
  edc-tests/runtime/mock-connector/src/main/java/org/eclipse/tractusx/edc/mock/MockServiceExtension.java
  gradle/libs.versions.toml
Labels: dependencies
