Repository eclipse-tractusx/tractusx-edc, pull requests merged in 2024-06, with the labels that each got.

#1277 fix: enable resource config & remove unnecessary configs from helm-charts
  charts/tractusx-connector-azure-vault/README.md
  charts/tractusx-connector-azure-vault/README.md.gotmpl
  charts/tractusx-connector-azure-vault/templates/deployment-controlplane.yaml
  charts/tractusx-connector-azure-vault/templates/deployment-dataplane.yaml
  charts/tractusx-connector-azure-vault/templates/networkpolicy.yaml
  charts/tractusx-connector-azure-vault/templates/service-controlplane.yaml
  charts/tractusx-connector-azure-vault/templates/service-dataplane.yaml
  charts/tractusx-connector-azure-vault/values.yaml
  charts/tractusx-connector-memory/README.md
  charts/tractusx-connector-memory/README.md.gotmpl
  charts/tractusx-connector-memory/templates/deployment-runtime.yaml
  charts/tractusx-connector-memory/templates/service-runtime.yaml
  charts/tractusx-connector-memory/values.yaml
  charts/tractusx-connector/README.md
  charts/tractusx-connector/README.md.gotmpl
  charts/tractusx-connector/templates/deployment-controlplane.yaml
  charts/tractusx-connector/templates/deployment-dataplane.yaml
  charts/tractusx-connector/templates/service-controlplane.yaml
  charts/tractusx-connector/templates/service-dataplane.yaml
  charts/tractusx-connector/values.yaml
  docs/migration/Version_0.5.x_0.7.x.md
  edc-tests/deployment/src/main/resources/helm/tractusx-connector-azure-vault-test.yaml
  edc-tests/deployment/src/main/resources/helm/tractusx-connector-memory-test.yaml
  edc-tests/deployment/src/main/resources/helm/tractusx-connector-test.yaml
Labels: documentation, helmcharts

#1365 feat(build): bump EDC version to latest nightly
  DEPENDENCIES
  edc-extensions/bdrs-client/src/main/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientAudienceMapper.java
  edc-extensions/bdrs-client/src/test/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientAudienceMapperTest.java
  edc-extensions/edr/edr-callback/src/main/java/org/eclipse/tractusx/edc/callback/ContractNegotiationCallback.java
  edc-extensions/edr/edr-callback/src/test/java/org/eclipse/tractusx/edc/callback/ContractNegotiationCallbackTest.java
  edc-extensions/tokenrefresh-handler/src/main/java/org/eclipse/tractusx/edc/common/tokenrefresh/TokenRefreshHandlerImpl.java
  edc-extensions/tokenrefresh-handler/src/test/java/org/eclipse/tractusx/edc/common/tokenrefresh/TokenRefreshHandlerImplTest.java
  edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/runtimes/ParticipantRuntime.java
  edc-tests/runtime/iatp/iatp-extensions/src/main/java/org/eclipse/tractusx/edc/iatp/TestAudienceMapper.java
  gradle/libs.versions.toml
Labels: enhancement

#1369 refactor(test): cleanup unneeded dependencies
  .github/workflows/verify.yaml
  DEPENDENCIES
  edc-tests/edc-dataplane/cloud-transfer-tests/build.gradle.kts
  edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/AzureBlobHelper.java
  edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/AzureToAzureTest.java
  edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/CloudTransferTest.java
  edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/MultiCloudTest.java
  edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/S3ToS3Test.java
  gradle/libs.versions.toml
Labels: refactoring

#1378 chore: bump EDC to v0.7.1
  DEPENDENCIES
  edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/MultiCloudTest.java
  edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/S3ToS3Test.java
  gradle/libs.versions.toml
Labels: enhancement, edc

#1382 feat: add s3 data-address validator to the runtime build
  DEPENDENCIES
  edc-controlplane/edc-controlplane-base/build.gradle.kts
  edc-dataplane/edc-dataplane-base/build.gradle.kts
  edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/AzureToAzureTest.java
  edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/MinioContainer.java
  edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/MultiCloudTest.java
  edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/ParticipantRuntime.java
  edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/S3ToS3Test.java
  edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/TestConstants.java
  gradle/libs.versions.toml
Labels: enhancement
