Repository eclipse-tractusx/tractusx-edc, pull requests merged in 2024-10, with the labels that each got.

#1598 Backport: fix: prevent default DCP identity extractor from being registered
  DEPENDENCIES
  charts/tractusx-connector-azure-vault/README.md
  charts/tractusx-connector-memory/README.md
  charts/tractusx-connector/README.md
  edc-extensions/iatp/tx-iatp/src/main/java/org/eclipse/tractusx/edc/iam/iatp/IatpIdentityExtension.java
  edc-extensions/iatp/tx-iatp/src/main/java/org/eclipse/tractusx/edc/iam/iatp/identity/IatpIdentityExtractor.java
  edc-extensions/iatp/tx-iatp/src/test/java/org/eclipse/tractusx/edc/iam/iatp/IatpIdentityExtensionTest.java
  edc-extensions/iatp/tx-iatp/src/test/java/org/eclipse/tractusx/edc/iam/iatp/identity/IatpIdentityExtractorTest.java
  edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/IdentityExtractorTest.java
Labels: bug

#1600 build: backport release workflow
  .github/actions/publish-tag-and-release/action.yml
  .github/actions/setup-helm/action.yml
  .github/workflows/manual-release-bugfix.yml
  .github/workflows/release.yml
  .github/workflows/trigger-docker-publish.yaml
  .github/workflows/trigger-maven-publish.yaml
Labels: refactoring

#1613 build: fix publish openapi ui
  .github/workflows/publish-openapi-ui.yml
Labels: github-actions

#1616 refactor: deprecate azure vault distribution
  .github/workflows/deployment-test.yaml
  .github/workflows/helm-lint.yaml
  .github/workflows/verify.yaml
  DEPENDENCIES
  charts/tractusx-connector-azure-vault/Chart.yaml
  charts/tractusx-connector-azure-vault/README.md
  edc-controlplane/edc-controlplane-postgresql-azure-vault/README.md
  edc-dataplane/edc-dataplane-azure-vault/README.md
Labels: refactoring

#1629 ci(test): avoid use of deprecated class
  .github/workflows/verify.yaml
  DEPENDENCIES
  edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/AzureToAzureTest.java
  edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/AzuriteContainer.java
  edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/CloudTransferTest.java
  edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/MultiCloudTest.java
  edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/S3ToS3Test.java
  edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/TestConstants.java
  edc-tests/edc-end2end/end2end-transfer-cloud/src/test/java/org/eclipse/tractusx/edc/tests/transfer/AzureBlobHelper.java
  edc-tests/edc-end2end/end2end-transfer-cloud/src/test/java/org/eclipse/tractusx/edc/tests/transfer/AzureToAzureEndToEndTest.java
  edc-tests/edc-end2end/end2end-transfer-cloud/src/test/java/org/eclipse/tractusx/edc/tests/transfer/AzuriteContainer.java
Labels: refactoring

#1645 build(deps): bump EDC to 0.10.0-20241022-SNAPSHOT
  DEPENDENCIES
  edc-extensions/bdrs-client/src/test/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientImplComponentTest.java
  edc-extensions/bpn-validation/bpn-validation-core/build.gradle.kts
  edc-extensions/bpn-validation/bpn-validation-core/src/main/java/org/eclipse/tractusx/edc/validation/businesspartner/BusinessPartnerNumberValidationExtension.java
  edc-extensions/bpn-validation/bpn-validation-core/src/main/java/org/eclipse/tractusx/edc/validation/businesspartner/BusinessPartnerValidationExtension.java
  edc-extensions/bpn-validation/bpn-validation-core/src/main/java/org/eclipse/tractusx/edc/validation/businesspartner/functions/BusinessPartnerGroupFunction.java
  edc-extensions/bpn-validation/bpn-validation-core/src/main/java/org/eclipse/tractusx/edc/validation/businesspartner/functions/BusinessPartnerNumberPermissionFunction.java
  edc-extensions/bpn-validation/bpn-validation-core/src/test/java/org/eclipse/tractusx/edc/validation/businesspartner/functions/BusinessPartnerGroupFunctionTest.java
  edc-extensions/bpn-validation/bpn-validation-core/src/test/java/org/eclipse/tractusx/edc/validation/businesspartner/functions/BusinessPartnerNumberPermissionFunctionTest.java
  edc-extensions/bpn-validation/bpn-validation-core/src/test/java/org/eclipse/tractusx/edc/validation/businesspartner/functions/TestParticipantAgentPolicyContext.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/CxPolicyExtension.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/common/AbstractDynamicCredentialConstraintFunction.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/dismantler/DismantlerCredentialConstraintFunction.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/framework/FrameworkAgreementCredentialConstraintFunction.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/membership/MembershipCredentialConstraintFunction.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/TestParticipantAgentPolicyContext.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/dismantler/DismantlerCredentialConstraintFunctionTest.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/framework/FrameworkAgreementCredentialConstraintFunctionTest.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/membership/MembershipCredentialConstraintFunctionTest.java
  edc-extensions/dcp/tx-dcp/src/main/java/org/eclipse/tractusx/edc/iam/iatp/identity/IatpIdentityExtractor.java
  edc-extensions/dcp/tx-dcp/src/main/java/org/eclipse/tractusx/edc/iam/iatp/scope/CredentialScopeExtractor.java
  edc-extensions/dcp/tx-dcp/src/test/java/org/eclipse/tractusx/edc/iam/iatp/identity/IatpIdentityExtractorTest.java
  edc-extensions/dcp/tx-dcp/src/test/java/org/eclipse/tractusx/edc/iam/iatp/scope/CredentialScopeExtractorTest.java
  edc-tests/e2e-fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/runtimes/ParticipantRuntime.java
  edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/DimHttpConsumerPullTest.java
  edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/IdentityExtractorTest.java
  edc-tests/runtime/iatp/runtime-memory-sts/src/main/java/org/eclipse/tractusx/edc/lifecycle/SecureTokenServiceExtension.java
  gradle/libs.versions.toml
Labels: dependencies

#1646 Update 07_edrs.md
  docs/usage/management-api-walkthrough/07_edrs.md
Labels: documentation

#1650 build(deps): bump EDC to 0.10.0
  DEPENDENCIES
  edc-controlplane/edc-controlplane-base/build.gradle.kts
  edc-extensions/bdrs-client/build.gradle.kts
  edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/build.gradle.kts
  edc-tests/e2e-fixtures/build.gradle.kts
  edc-tests/runtime/iatp/runtime-memory-sts/build.gradle.kts
  gradle/libs.versions.toml
  samples/edc-dast/edc-dast-extensions/build.gradle.kts
Labels: dependencies
