Repository eclipse-tractusx/tractusx-edc, pull requests merged in 2024-02, with the labels that each got.

#1014 docs: fix action use in ODRL payloads
  docs/usage/management-api-walkthrough/02_policies.md
  docs/usage/management-api-walkthrough/07_edrs.md
  docs/usage/management-api-walkthrough/08_contractagreements.md
Labels: documentation

#1017 chore: update dependencies
  DEPENDENCIES
Labels: dependencies

#1026 refactor: remove unused mockito-inline dependency
  DEPENDENCIES
  edc-extensions/transferprocess-sftp-client/build.gradle.kts
  edc-extensions/transferprocess-sftp-common/build.gradle.kts
  edc-extensions/transferprocess-sftp-provisioner/build.gradle.kts
  gradle/libs.versions.toml
Labels: refactoring

#1024 fix: migrate asset json properties from array to map
  edc-extensions/postgresql-migration/build.gradle.kts
  edc-extensions/postgresql-migration/src/main/java/org/eclipse/tractusx/edc/postgresql/migration/AbstractPostgresqlMigrationExtension.java
  edc-extensions/postgresql-migration/src/main/java/org/eclipse/tractusx/edc/postgresql/migration/FlywayManager.java
  edc-extensions/postgresql-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/asset/V0_0_6__Transform_Property_Array_To_Map.sql
  edc-extensions/postgresql-migration/src/test/java/org/eclipse/tractusx/edc/postgresql/migration/AssetPostgresqlMigrationExtensionTest.java
  edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/edr/AbstractDeleteEdrTest.java
  gradle/libs.versions.toml
Labels: bug

#1052 chore: make license header regex more permissive
  resources/hashtag.header
  resources/java.header
Labels: enhancement

#1053 feat: implement new Policy eval fct for FrameworkAgreement
  DEPENDENCIES
  edc-extensions/cx-policy/build.gradle.kts
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/framework/FrameworkAgreementConstraintFunction.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/framework/FrameworkAgreementConstraintFunctionTest.java
  gradle/libs.versions.toml
  spi/ssi-spi/src/main/java/org/eclipse/tractusx/edc/iam/ssi/spi/jsonld/CredentialsNamespaces.java
Labels: enhancement, iatp

#1059 feat: add Dismantler constraint eval function
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/common/AbstractDynamicConstraintFunction.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/common/CredentialTypePredicate.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/dismantler/DismantlerConstraintFunction.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/framework/FrameworkAgreementConstraintFunction.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/CredentialFunctions.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/dismantler/DismantlerConstraintFunctionTest.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/framework/FrameworkAgreementConstraintFunctionTest.java
Labels: enhancement, iatp
