Repository eclipse-tractusx/tractusx-edc, pull requests merged in 2025-08, with the labels that each got.

#2089 feat(constraints): add validation for new constraints
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/CxPolicyExtension.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/jurisdictionlocation/JurisdictionLocationConstraintFunction.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/jurisdictionlocation/JurisdictionLocationReferenceConstraintFunction.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/liability/LiabilityConstraintFunction.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/managedlegalentity/ManagedLegalEntityBpnlConstraintFunction.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/managedlegalentity/ManagedLegalEntityRegionConstraintFunction.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/membership/MembershipCredentialConstraintFunction.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/jurisdictionlocation/JurisdictionLocationConstraintFunctionTest.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/jurisdictionlocation/JurisdictionLocationReferenceConstraintFunctionTest.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/liability/LiabilityConstraintFunctionTest.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/managedlegalentity/ManagedLegalEntityBpnlConstraintFunctionTest.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/managedlegalentity/ManagedLegalEntityRegionConstraintFunctionTest.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/membership/MembershipCredentialConstraintFunctionTest.java
  edc-tests/e2e/policy-tests/src/test/java/org/eclipse/tractusx/edc/tests/policy/PolicyDefinitionEndToEndTest.java
Labels: enhancement

#2092 feat(constraint): add validation for framework constraint
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/framework/FrameworkAgreementCredentialConstraintFunction.java
  edc-tests/e2e/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/AbstractIatpConsumerPullTest.java
  edc-tests/e2e/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/iatp/harness/DataspaceIssuer.java
  edc-tests/e2e/policy-tests/src/test/java/org/eclipse/tractusx/edc/tests/policy/PolicyDefinitionEndToEndTest.java
Labels: enhancement, breaking change

#2138 docs: non-finite-provider-push DMA walkthrough
  docs/usage/management-api-walkthrough/10_nonfiniteproviderpush/10_nonfiniteproviderpush.md
  docs/usage/management-api-walkthrough/10_nonfiniteproviderpush/assets/non-finite-provider-push.png
  docs/usage/management-api-walkthrough/10_nonfiniteproviderpush/assets/pipeline-service-data-transfer.png
Labels: documentation

#2101 feat: add policy schema validators
  edc-extensions/bpn-validation/bpn-validation-core/src/main/java/org/eclipse/tractusx/edc/validation/businesspartner/functions/BusinessPartnerNumberPermissionFunction.java
  edc-extensions/bpn-validation/bpn-validation-core/src/test/java/org/eclipse/tractusx/edc/validation/businesspartner/functions/BusinessPartnerNumberPermissionFunctionTest.java
  edc-extensions/cx-policy/build.gradle.kts
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/CxPolicyExtension.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/validator/AccessPolicyValidator.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/validator/ActionTypeIs.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/validator/ArrayIsEmpty.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/validator/AtLeastOneRuleExists.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/validator/AtomicConstraintValidator.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/validator/ConstraintValidator.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/validator/CxPolicyDefinitionValidator.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/validator/LeftOperandValidator.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/validator/LogicalConstraintValidator.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/validator/PolicyTypeResolver.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/validator/PolicyValidationConstants.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/validator/TypedMandatoryArray.java
  edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/validator/UsagePolicyValidator.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/validator/AccessPolicyValidatorTest.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/validator/ActionTypeIsTest.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/validator/ArrayIsEmptyTest.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/validator/AtomicConstraintValidatorTest.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/validator/ConstraintValidatorTest.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/validator/CxPolicyDefinitionValidatorTest.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/validator/LeftOperandValidatorTest.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/validator/LogicalConstraintValidatorTest.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/validator/PolicyTypeResolverTest.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/validator/TypedMandatoryArrayTest.java
  edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/validator/UsagePolicyValidatorTest.java
  edc-extensions/cx-policy/src/testFixtures/java/org/eclipse/tractusx/edc/policy/cx/validator/PolicyBuilderFixtures.java
  edc-tests/e2e-fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/helpers/PolicyHelperFunctions.java
  edc-tests/e2e/catalog-tests/src/test/java/org/eclipse/tractusx/edc/tests/catalog/CatalogTest.java
  edc-tests/e2e/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/AbstractIatpConsumerPullTest.java
  edc-tests/e2e/policy-tests/src/test/java/org/eclipse/tractusx/edc/tests/policy/PolicyDefinitionEndToEndTest.java
  edc-tests/e2e/transfer-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/RetireAgreementTest.java
Labels: enhancement, breaking change

#2179 build: adapt maven publication to the new flow
  .github/workflows/trigger-maven-publish.yaml
  gradle/libs.versions.toml
Labels: enhancement

#2191 feat: add supported types for trusted issuer
  charts/tractusx-connector-memory/README.md
  charts/tractusx-connector-memory/templates/deployment-runtime.yaml
  charts/tractusx-connector-memory/values.yaml
  charts/tractusx-connector/README.md
  charts/tractusx-connector/templates/deployment-controlplane.yaml
  charts/tractusx-connector/values.yaml
Labels: enhancement

#2194 docs: updated repository structure
  docs/development/repository-structure.md
Labels: documentation

#2195 fix: automatic PR labeling for breaking changes on release notes
  .github/release.yaml
Labels: bug
