Repository eclipse-tractusx/tractusx-edc, pull requests merged in 2025-05, with the labels that each got.

#1937 refactor: cleanup dependencies
  edc-controlplane/edc-controlplane-base/build.gradle.kts
  edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/build.gradle.kts
  edc-controlplane/edc-runtime-memory/build.gradle.kts
  edc-dataplane/edc-dataplane-base/build.gradle.kts
  edc-dataplane/edc-dataplane-hashicorp-vault/build.gradle.kts
  edc-tests/e2e-fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/participant/TractusxParticipantBase.java
  edc-tests/e2e/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/CredentialSpoofTest.java
  edc-tests/e2e/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/IatpParticipants.java
  edc-tests/e2e/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/IdentityExtractorTest.java
  edc-tests/e2e/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/iatp/harness/DataspaceIssuer.java
  edc-tests/runtime/iatp/runtime-memory-sts/build.gradle.kts
  gradle/libs.versions.toml
  samples/multi-tenancy/src/test/resources/tenants.properties
  settings.gradle.kts
Labels: refactoring

#1939 fix: avoid potential deadlocks
  edc-extensions/bdrs-client/src/main/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientImpl.java
Labels: refactoring

#1941 build(deps): bump gradle wrapper to 8.14
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#1940 refactor: avoid deferenced var may be null warning
  edc-extensions/dataplane/dataplane-proxy/edc-dataplane-proxy-consumer-api/src/main/java/org/eclipse/tractusx/edc/dataplane/proxy/consumer/api/asset/ConsumerAssetRequestController.java
Labels: refactoring

#1954 feat: make release workflow manual
  .github/workflows/codeql.yaml
  .github/workflows/manual-release-bugfix.yml
  .github/workflows/release.yml
Labels: enhancement

#1975 build: fix dependencies check
  .github/actions/generate-and-check-dependencies/action.yml
  DEPENDENCIES
  dependency-list
Labels: bug

#1977 build: permit release from release/* branches
  .github/workflows/release.yml
Labels: enhancement

#1987 fix: exclude sql target node extension
  edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/build.gradle.kts
Labels: bug

#1995 build(deps): bump EDC to 0.13.0
  edc-extensions/bdrs-client/src/main/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientImpl.java
  edc-extensions/dcp/tx-dcp-sts-dim/src/main/java/org/eclipse/tractusx/edc/iam/dcp/sts/dim/DimSecureTokenService.java
  edc-extensions/dcp/tx-dcp-sts-dim/src/test/java/org/eclipse/tractusx/edc/iam/dcp/sts/dim/DimSecureTokenServiceTest.java
  edc-extensions/tokenrefresh-handler/src/main/java/org/eclipse/tractusx/edc/common/tokenrefresh/TokenRefreshHandlerImpl.java
  gradle/libs.versions.toml
Labels: dependencies
