Repository eclipse-tractusx/tractusx-edc, pull requests merged in 2025-03, with the labels that each got.

#1859 refactor: cleanup test dependencies
  DEPENDENCIES
  edc-extensions/agreements/retirement-evaluation-core/build.gradle.kts
  edc-extensions/bpn-validation/bpn-validation-core/build.gradle.kts
  edc-tests/e2e-fixtures/build.gradle.kts
  edc-tests/runtime/mock-connector/build.gradle.kts
  gradle/libs.versions.toml
  spi/edr-spi/build.gradle.kts
Labels: refactoring

#1831 feat: Add workflow to check dependencies before release.
  .github/actions/generate-and-check-dependencies/action.yml
  .github/workflows/check-dependencies.yaml
  .github/workflows/draft-release.yaml
Labels: enhancement

#1862 ci: fix flaky tests
  edc-tests/e2e-fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/aws/MinioExtension.java
  edc-tests/e2e-fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/extension/VaultSeedExtension.java
  edc-tests/e2e-fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/participant/TractusxIatpParticipantBase.java
  edc-tests/e2e-fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/participant/TractusxParticipantBase.java
  edc-tests/e2e-fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/transfer/ConsumerPullBaseTest.java
  edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/AbstractIatpConsumerPullTest.java
  edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/CredentialSpoofTest.java
  edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/DimConsumerPullTest.java
  edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/IatpParticipants.java
  edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/StsConsumerPullTest.java
  edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/iatp/harness/DataspaceIssuer.java
  edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/iatp/harness/IatpHelperFunctions.java
  edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/iatp/harness/IatpParticipant.java
  edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/iatp/harness/StsParticipant.java
  edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/iatp/runtime/Runtimes.java
  edc-tests/edc-controlplane/transfer-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/TransferPullEndToEndTest.java
  edc-tests/edc-dataplane/cloud-transfer-tests/build.gradle.kts
  edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/AzureToAzureTest.java
  edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/MultiCloudTest.java
  edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/RuntimeConfig.java
  edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/S3ToS3Test.java
  edc-tests/edc-dataplane/edc-dataplane-tokenrefresh-tests/build.gradle.kts
  edc-tests/edc-dataplane/edc-dataplane-tokenrefresh-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/e2e/DataPlaneTokenRefreshEndToEndTest.java
  edc-tests/edc-dataplane/edc-dataplane-tokenrefresh-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/e2e/RuntimeConfig.java
  edc-tests/edc-end2end/end2end-transfer-cloud/src/test/java/org/eclipse/tractusx/edc/tests/transfer/S3ToS3EndToEndTest.java
  edc-tests/runtime/extensions/build.gradle.kts
  edc-tests/runtime/extensions/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  edc-tests/runtime/iatp/runtime-memory-iatp-dim-ih/build.gradle.kts
  edc-tests/runtime/iatp/runtime-memory-iatp-dim/build.gradle.kts
  edc-tests/runtime/iatp/runtime-memory-iatp-ih/build.gradle.kts
  edc-tests/runtime/iatp/runtime-memory-sts/build.gradle.kts
  edc-tests/runtime/runtime-memory/build.gradle.kts
  edc-tests/runtime/runtime-postgresql/build.gradle.kts
  samples/edc-dast/edc-dast-extensions/src/main/java/org/eclipse/tractusx/edc/dast/VaultSeedExtension.java
  samples/edc-dast/edc-dast-extensions/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  samples/edc-dast/edc-dast-runtime/configuration.properties
  settings.gradle.kts
Labels: refactoring

#1866 refactor: remove DEPENDENCIES file
  DEPENDENCIES
  NOTICE.md
Labels: dependencies
