Repository eclipse-tractusx/tractusx-edc, pull requests merged in 2025-02, with the labels that each got.

#1782 ci: fix ITs
  DEPENDENCIES
  edc-extensions/bdrs-client/src/test/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientImplComponentTest.java
Labels: refactoring

#1764 feat: Update EDC version to 0.11.0
  DEPENDENCIES
  edc-extensions/bdrs-client/src/test/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientImplComponentTest.java
  edc-extensions/bdrs-client/src/test/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientImplTest.java
  edc-tests/e2e-fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/ParticipantEdrApi.java
  edc-tests/e2e-fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/participant/TractusxIatpParticipantBase.java
  edc-tests/e2e-fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/participant/TractusxParticipantBase.java
  edc-tests/edc-controlplane/catalog-tests/src/test/java/org/eclipse/tractusx/edc/tests/catalog/FederatedCatalogTest.java
  edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/AbstractIatpConsumerPullTest.java
  edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/iatp/harness/DataspaceIssuer.java
  gradle/libs.versions.toml
  samples/edc-dast/edc-dast-extensions/src/main/java/org/eclipse/tractusx/edc/dast/DastSeedExtension.java
Labels: dependencies

#1786 feat: add contract definition empty asset selector validator
  DEPENDENCIES
  edc-controlplane/edc-controlplane-base/build.gradle.kts
  edc-extensions/validators/empty-asset-selector/build.gradle.kts
  edc-extensions/validators/empty-asset-selector/src/main/java/org/eclipse/tractusx/edc/validators/emptyassetselector/EmptyAssetSelectorBlockerExtension.java
  edc-extensions/validators/empty-asset-selector/src/main/java/org/eclipse/tractusx/edc/validators/emptyassetselector/EmptyAssetSelectorValidator.java
  edc-extensions/validators/empty-asset-selector/src/main/java/org/eclipse/tractusx/edc/validators/emptyassetselector/README.md
  edc-extensions/validators/empty-asset-selector/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  edc-extensions/validators/empty-asset-selector/src/test/java/org/eclipse/tractusx/edc/validators/emptyassetselector/EmptyAssetSelectorValidatorTest.java
  edc-tests/edc-controlplane/validator-tests/build.gradle.kts
  edc-tests/edc-controlplane/validator-tests/src/test/java/org/eclipse/tractusx/edc/tests/validators/EmptyAssetSelectorValidatorTest.java
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: enhancement

#1805 docs: Added 0.8.X -> 0.9.X migration guide
  DEPENDENCIES
  docs/migration/Version_0.8.x_0.9.x.md
Labels: documentation

#1816 docs: update the openApiSpecs urls
  .tractusx
  DEPENDENCIES
Labels: documentation

#1817 build(deps): force transitive dependencies to fix security checks
  DEPENDENCIES
  build.gradle.kts
Labels: dependencies
